#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /home\.css
  static_files: home.css
  upload: home\.css

- url: /images
  static_dir:  images

- url: /themes
  static_dir: themes

- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest